---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - yucloudnative.io
  resources:
  - lazysidecars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yucloudnative.io
  resources:
  - lazysidecars/finalizers
  verbs:
  - update
- apiGroups:
  - yucloudnative.io
  resources:
  - lazysidecars/status
  verbs:
  - get
  - patch
  - update
