apiVersion: yucloudnative.io/v1
kind: LazySidecar
metadata:
  name: lazysidecar-sample
spec:
  egressHosts:
  - default/test.default.svc.cluster.local
  middlewareList:
    - serviceName: mysql
      namespace: mysql-ns
      port: 3306
      type: MYSQL
      protocol: HTTP
  workloadSelector:
    foo: bar123
